import { useState, useEffect } from 'react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid
} from 'recharts';
import { DollarSign, Package, TrendingUp, Trophy } from 'lucide-react';
import '../styles/salesReport.css';

export default function SalesReport() {
  const [report, setReport] = useState(null);

  useEffect(() => {
    const fetchReport = async () => {
      const response = await fetch('/admin/generate-sales-report');
      const data = await response.json();

      if (data.status === 'success') {
        setReport(data.report);
      } else {
        alert('Error fetching report: ' + data.message);
      }
    };

    fetchReport();
  }, []);

  if (!report) {
    return (
      <div className="sales-loading">
        Loading sales report...
      </div>
    );
  }

  const totalItems = report.earnings_by_item?.length || 0;
  const totalBrands = report.earnings_by_brand?.length || 0;
  const bestSellingCount = report.best_selling_items?.length || 0;

  return (
    <div className="sales-page">
      <div className="sales-header">
        <div>
          <h2>Sales Report</h2>
          <p>Review total earnings, brand performance, item revenue, and best-selling listings.</p>
        </div>
      </div>

      <div className="sales-kpi-grid">
        <div className="sales-kpi-card primary">
          <DollarSign size={22} />
          <span>Total Earnings</span>
          <strong>${Number(report.total_earnings).toFixed(2)}</strong>
        </div>

        <div className="sales-kpi-card">
          <Package size={22} />
          <span>Items Sold</span>
          <strong>{totalItems}</strong>
        </div>

        <div className="sales-kpi-card">
          <TrendingUp size={22} />
          <span>Brands</span>
          <strong>{totalBrands}</strong>
        </div>

        <div className="sales-kpi-card">
          <Trophy size={22} />
          <span>Best Sellers</span>
          <strong>{bestSellingCount}</strong>
        </div>
      </div>

      <section className="sales-card">
        <div className="sales-section-header">
          <h3>Earnings by Brand</h3>
          <p>Revenue grouped by product brand.</p>
        </div>

        <ResponsiveContainer width="100%" height={320}>
          <BarChart
            data={report.earnings_by_brand}
            margin={{ top: 20, right: 30, left: 0, bottom: 5 }}
          >
            <CartesianGrid strokeDasharray="3 3" vertical={false} />
            <XAxis dataKey="brand" />
            <YAxis />
            <Tooltip
              formatter={(value) => [`$${Number(value).toFixed(2)}`, 'Earnings']}
              contentStyle={{
                backgroundColor: '#ffffff',
                border: '1px solid #e5e7eb',
                borderRadius: '12px'
              }}
              labelStyle={{ fontWeight: 'bold' }}
            />
            <Bar
              dataKey="total"
              fill="#2563eb"
              barSize={42}
              radius={[8, 8, 0, 0]}
            />
          </BarChart>
        </ResponsiveContainer>
      </section>

      <div className="sales-table-grid">
        <section className="sales-card">
          <div className="sales-section-header">
            <h3>Earnings by Item</h3>
            <p>Revenue generated by each item.</p>
          </div>

          <div className="sales-table-wrapper">
            <table className="sales-modern-table">
              <thead>
                <tr>
                  <th>Item</th>
                  <th>Earnings</th>
                </tr>
              </thead>

              <tbody>
                {report.earnings_by_item.map((item, idx) => (
                  <tr key={idx}>
                    <td>{item.item_name}</td>
                    <td>
                      <span className="earnings-pill">
                        ${Number(item.earnings).toFixed(2)}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section className="sales-card">
          <div className="sales-section-header">
            <h3>Best-Selling Items</h3>
            <p>Items ranked by total number of bids.</p>
          </div>

          <div className="sales-table-wrapper">
            <table className="sales-modern-table">
              <thead>
                <tr>
                  <th>Item</th>
                  <th>Total Bids</th>
                </tr>
              </thead>

              <tbody>
                {report.best_selling_items.map((item, idx) => (
                  <tr key={idx}>
                    <td>{item.item_name}</td>
                    <td>
                      <span className="bids-pill">
                        {item.total_bids}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      </div>
    </div>
  );
}